# **Ensemble of Local Model-Agnostic Explanation Models for Robust Local Feature Importance Ranking**

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [17]:
import numpy as np
np.set_printoptions(suppress=True)
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import NearestNeighbors

# Explainable AI tools:
import shap
from lime.lime_tabular import LimeTabularExplainer
from alibi.explainers import AnchorTabular # why not used the original anchor package?

from scipy.stats import spearmanr, pearsonr

from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam  # Import the Adam optimizer

from tools.topsis import Topsis

In [3]:
# Configure pandas output
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 40)

# Data Loading and Preprocessing

### Data loading and summarizing

In [ ]:
original_data = pd.read_csv('german_credit_data_updated.csv')

# Dataset overview - German Credit Risk (from Kaggle):
# 1. Age (numeric)
# 2. Sex (text: male, female)
# 3. Job (numeric: 0 - unskilled and non-resident, 1 - unskilled and resident, 2 - skilled, 3 - highly skilled)
# 4. Housing (text: own, rent, or free)
# 5. Saving accounts (text - little, moderate, quite rich, rich)
# 6. Checking account (numeric, in DM - Deutsch Mark)
# 7. Credit amount (numeric, in DM)
# 8. Duration (numeric, in month)
# 9. Purpose (text: car, furniture/equipment, radio/TV, domestic appliances, repairs, education, business, vacation/others)

display(original_data.head())
display(original_data.describe())
display(original_data.info())

# Display the unique values of thprecision=3, e categorical features:
print('Unique values of the categorical features:')
for col in original_data.select_dtypes(include='object'):
    print(f'\t- {col}: {original_data[col].unique()}')

Unnamed: 0  Age     Sex  Job Housing Saving accounts Checking account  \
0           0   67    male    2     own             NaN           little   
1           1   22  female    2     own          little         moderate   
2           2   49    male    1     own          little              NaN   
3           3   45    male    2    free          little           little   
4           4   53    male    2    free          little           little   

   Credit amount  Duration              Purpose  Credit Risk  
0           1169         6             radio/TV            1  
1           5951        48             radio/TV            2  
2           2096        12            education            1  
3           7882        42  furniture/equipment            1  
4           4870        24                  car            2

Unnamed: 0         Age         Job  Credit amount    Duration  \
count  954.000000  954.000000  954.000000     954.000000  954.000000   
mean   476.500000   35.501048    1.909853    3279.112159   20.780922   
std    275.540378   11.379668    0.649681    2853.315158   12.046483   
min      0.000000   19.000000    0.000000     250.000000    4.000000   
25%    238.250000   27.000000    2.000000    1360.250000   12.000000   
50%    476.500000   33.000000    2.000000    2302.500000   18.000000   
75%    714.750000   42.000000    2.000000    3975.250000   24.000000   
max    953.000000   75.000000    3.000000   18424.000000   72.000000   

       Credit Risk  
count   954.000000  
mean      1.302935  
std       0.459768  
min       1.000000  
25%       1.000000  
50%       1.000000  
75%       2.000000  
max       2.000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 954 entries, 0 to 953
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Unnamed: 0        954 non-null    int64 
 1   Age               954 non-null    int64 
 2   Sex               954 non-null    object
 3   Job               954 non-null    int64 
 4   Housing           954 non-null    object
 5   Saving accounts   779 non-null    object
 6   Checking account  576 non-null    object
 7   Credit amount     954 non-null    int64 
 8   Duration          954 non-null    int64 
 9   Purpose           954 non-null    object
 10  Credit Risk       954 non-null    int64 
dtypes: int64(6), object(5)
memory usage: 82.1+ KB


None

Unique values of the categorical features:
	- Sex: ['male' 'female']
	- Housing: ['own' 'free' 'rent']
	- Saving accounts: [nan 'little' 'quite rich' 'rich' 'moderate']
	- Checking account: ['little' 'moderate' nan 'rich']
	- Purpose: ['radio/TV' 'education' 'furniture/equipment' 'car' 'business'
 'domestic appliances' 'repairs' 'vacation/others']


### Data preprocessing

In [5]:
preprocessed_data = original_data.copy()

# For savings and checking accounts, we will replace the missing values with 'none':
preprocessed_data['Saving accounts'].fillna('none', inplace=True)
preprocessed_data['Checking account'].fillna('none', inplace=True)

# Dropping index column:
preprocessed_data.drop(columns=['Unnamed: 0'], inplace=True)

# Using pd.dummies to one-hot-encode the categorical features
preprocessed_data["Job"] = preprocessed_data["Job"].map({0: 'unskilled_nonresident', 1: 'unskilled_resident',
                                                         2: 'skilled', 3: 'highlyskilled'})

categorical_features = preprocessed_data.select_dtypes(include='object').columns
numerical_features = preprocessed_data.select_dtypes(include='number').columns.drop('Credit Risk')
print(f'Categorical features: {categorical_features}')
print(f'Numerical features: {numerical_features}')

preprocessed_data = pd.get_dummies(preprocessed_data, columns=categorical_features, dtype='int64')

# Remapping the target variable to 0 and 1:
preprocessed_data['Credit Risk'] = preprocessed_data['Credit Risk'].map({1: 0, 2: 1})

# Make sure all column names are valid python identifiers (important for pd.query() calls):
preprocessed_data.columns = preprocessed_data.columns.str.replace(' ', '_')
preprocessed_data.columns = preprocessed_data.columns.str.replace('/', '_')

# Normalizing the data
scaler = StandardScaler()
scaled_preprocessed_data = scaler.fit_transform(preprocessed_data)

display(preprocessed_data.head())
display(preprocessed_data.info())

display(scaled_preprocessed_data)


Categorical features: Index(['Sex', 'Job', 'Housing', 'Saving accounts', 'Checking account',
       'Purpose'],
      dtype='object')
Numerical features: Index(['Age', 'Credit amount', 'Duration'], dtype='object')


Age  Credit_amount  Duration  Credit_Risk  Sex_female  Sex_male  \
0   67           1169         6            0           0         1   
1   22           5951        48            1           1         0   
2   49           2096        12            0           0         1   
3   45           7882        42            0           0         1   
4   53           4870        24            1           0         1   

   Job_highlyskilled  Job_skilled  Job_unskilled_nonresident  \
0                  0            1                          0   
1                  0            1                          0   
2                  0            0                          0   
3                  0            1                          0   
4                  0            1                          0   

   Job_unskilled_resident  Housing_free  Housing_own  Housing_rent  \
0                       0             0            1             0   
1                       0             0            1             0   
2                       1             0            1             0   
3                       0             1            0             0   
4                       0             1            0             0   

   Saving_accounts_little  Saving_accounts_moderate  Saving_accounts_none  \
0                       0                         0                     1   
1                       1                         0                     0   
2                       1                         0                     0   
3                       1                         0                     0   
4                       1                         0                     0   

   Saving_accounts_quite_rich  Saving_accounts_rich  Checking_account_little  \
0                           0                     0                        1   
1                           0                     0                        0   
2                           0                     0                        0   
3                           0                     0                        1   
4                           0                     0                        1   

   Checking_account_moderate  Checking_account_none  Checking_account_rich  \
0                          0                      0                      0   
1                          1                      0                      0   
2                          0                      1                      0   
3                          0                      0                      0   
4                          0                      0                      0   

   Purpose_business  Purpose_car  Purpose_domestic_appliances  \
0                 0            0                            0   
1                 0            0                            0   
2                 0            0                            0   
3                 0            0                            0   
4                 0            1                            0   

   Purpose_education  Purpose_furniture_equipment  Purpose_radio_TV  \
0                  0                            0                 1   
1                  0                            0                 1   
2                  1                            0                 0   
3                  0                            1                 0   
4                  0                            0                 0   

   Purpose_repairs  Purpose_vacation_others  
0                0                        0  
1                0                        0  
2                0                        0  
3                0                        0  
4                0                        0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 954 entries, 0 to 953
Data columns (total 30 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          954 non-null    int64
 1   Credit_amount                954 non-null    int64
 2   Duration                     954 non-null    int64
 3   Credit_Risk                  954 non-null    int64
 4   Sex_female                   954 non-null    int64
 5   Sex_male                     954 non-null    int64
 6   Job_highlyskilled            954 non-null    int64
 7   Job_skilled                  954 non-null    int64
 8   Job_unskilled_nonresident    954 non-null    int64
 9   Job_unskilled_resident       954 non-null    int64
 10  Housing_free                 954 non-null    int64
 11  Housing_own                  954 non-null    int64
 12  Housing_rent                 954 non-null    int64
 13  Saving_accounts_little       954 non-null    int64

None

array([[ 2.7694545 , -0.7399179 , -1.22763429, ...,  1.62518349,
        -0.14633276, -0.11286653],
       [-1.18704073,  0.93690642,  2.26068929, ...,  1.62518349,
        -0.14633276, -0.11286653],
       [ 1.18685641, -0.41486224, -0.72930235, ..., -0.61531514,
        -0.14633276, -0.11286653],
       ...,
       [-1.0111965 , -0.39768023,  1.26402541, ..., -0.61531514,
        -0.14633276, -0.11286653],
       [-0.65950803,  0.29240557,  0.26736153, ..., -0.61531514,
        -0.14633276, -0.11286653],
       [-0.83535227,  2.69823821,  1.26402541, ..., -0.61531514,
        -0.14633276, -0.11286653]])

### Splitting the data into training and testing sets:

In [6]:
y = preprocessed_data['Credit_Risk']
X = preprocessed_data.drop(columns='Credit_Risk')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Sklearn Model Fitting

In [7]:
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print(f'ROC AUC: {roc_auc_score(y_test, y_pred)}')

Accuracy: 0.7696335078534031
ROC AUC: 0.6830357142857143


# Algorithm Implementation
Given a dataset, an ML model trained on this dataset (whose predictions we want to explain), and a set of explanation tools from which the aggregate explanation model will be built:

1. Apply each explanation model to the instance whose prediction is to be explained, obtaining a feature importance ranking for each explanation model.
2. Generate a variation of the original dataset by introducing noise.
3. Repeat step 1 on this noisy dataset to obtain a new set of feature importance rankings.
4. Assess the robustness of each explanation model by comparing its feature importance ranking on the original data with the ranking on the noisy data.
5. Finally, compute an aggregate explanation ranking by taking the weighted average of the rankings obtained in step 1, with the weights based on each model's stability (determined in step 4).

### Step 1
Apply each explanation model to the instance whose prediction is to be explained, obtaining a feature importance ranking for each explanation model.

In [8]:
class FeatureImportanceCalculator():
    def __init__(self, clf, X_train: pd.DataFrame | np.ndarray, predict_proba_function: callable = None):
        self.X_train = X_train
        self.clf = clf
        
        if predict_proba_function is not None:
            self.predict_proba_function = predict_proba_function
        elif hasattr(clf, 'predict_proba') and predict_proba_function is None:
            self.predict_proba_function = clf.predict_proba
        else:
            raise ValueError('The classifier does not have a predict_proba method and no predict_proba_function was provided.')
        
        self.anchor_explainer = AnchorTabular(predictor=self.predict_proba_function, feature_names=self.X_train.columns) # TODO: fix parameters
        self.anchor_explainer.fit(self.X_train.values)


    def get_lime_ranking(self, instance_data_row) -> pd.DataFrame:
        """
        Returns a DataFrame with the feature importance ranking using LIME, ordered by abs(importance).
        """
        
        explainer = LimeTabularExplainer(self.X_train.values, feature_names=self.X_train.columns, discretize_continuous=False)
        lime_exp = explainer.explain_instance(instance_data_row, self.predict_proba_function, num_features=len(self.X_train.columns))
        
        ranking = pd.DataFrame(lime_exp.as_list(), columns=['feature', 'score'])

        return ranking
    
    def get_shap_ranking(self, instance_data_row, explainer_type: shap.Explainer = shap.KernelExplainer, **additional_explainer_args) -> pd.DataFrame:
        """
        Returns a DataFrame with the feature importance ranking using SHAP, ordered by abs(importance).
        """
        explainer = explainer_type(self.clf, self.X_train, **additional_explainer_args)
        shap_values = explainer.shap_values(instance_data_row)

        ranking = pd.DataFrame(list(zip(self.X_train.columns, shap_values[:, 0])), columns=['feature', 'score'])
        ranking = ranking.sort_values(by='score', ascending=False, key=lambda x: abs(x)).reset_index(drop=True)
        
        return ranking
    
    def get_anchor_ranking(self, instance_data_row: pd.Series | np.ndarray) -> pd.DataFrame:
        """
        Returns a DataFrame with the feature importance ranking using Anchor, ordered by abs(importance).
        Feature importance is not directly available in the AnchorTabular class. In order to obtain it, we can
        calculate the percentage of rows in the training data that are not covered by the anchor rule. The more
        rows that are not covered, the more important the feature is.
        """

        if isinstance(instance_data_row, pd.Series):
            instance_data_row = instance_data_row.to_numpy()

        feature_importances = {feature: 0 for feature in self.X_train.columns}
        explanation = self.anchor_explainer.explain(instance_data_row)
        
        for rule in explanation.anchor:
            # Extract the feature name from the rule string
            # This method won't work for column names that have spaces in them or that don't contain any letters
            for expression_element in rule.split():
                if any(c.isalpha() for c in expression_element):
                    referenced_feature = expression_element
                    break

            rule_coverage = X_train.query(rule).shape[0] / X_train.shape[0]
            feature_importances[referenced_feature] = 1 - rule_coverage
        
        return pd.DataFrame(list(feature_importances.items()), columns=['feature', 'score']).sort_values(by='score', ascending=False).reset_index(drop=True)

In [9]:
# Example usage:
feature_importances = FeatureImportanceCalculator(clf, X_train)
    
sample_idx = 0
lime_ranking = feature_importances.get_lime_ranking(X_test.iloc[sample_idx])
shap_ranking = feature_importances.get_shap_ranking(X_test.iloc[sample_idx], explainer_type=shap.TreeExplainer)
anchor_ranking = feature_importances.get_anchor_ranking(X_test.iloc[sample_idx])

print('LIME ranking:')
display(lime_ranking)
print('SHAP ranking:')
display(shap_ranking)
print('Anchor ranking:')
display(anchor_ranking)

LIME ranking:


feature     score
0         Checking_account_none -0.057718
1                      Duration  0.055175
2       Checking_account_little  0.037656
3                           Age -0.023477
4     Checking_account_moderate  0.018176
5                   Housing_own -0.012884
6        Saving_accounts_little  0.012801
7                      Sex_male -0.011548
8                 Credit_amount  0.011079
9              Purpose_radio_TV -0.008546
10                   Sex_female  0.007416
11                 Housing_rent  0.007017
12         Saving_accounts_none -0.004974
13                  Purpose_car  0.003918
14             Purpose_business  0.003108
15                 Housing_free  0.003051
16   Saving_accounts_quite_rich -0.002839
17                  Job_skilled  0.002767
18  Purpose_domestic_appliances  0.002130
19  Purpose_furniture_equipment -0.001384
20              Purpose_repairs -0.000921
21     Saving_accounts_moderate  0.000893
22    Job_unskilled_nonresident  0.000623
23            Job_highlyskilled -0.000553
24            Purpose_education  0.000185
25         Saving_accounts_rich  0.000156
26      Purpose_vacation_others  0.000119
27       Job_unskilled_resident -0.000029
28        Checking_account_rich -0.000006

SHAP ranking:


feature     score
0                      Duration  0.051965
1         Checking_account_none -0.048818
2                           Age  0.044427
3       Checking_account_little  0.030740
4     Checking_account_moderate -0.025005
5                 Credit_amount  0.018809
6      Saving_accounts_moderate  0.011132
7   Purpose_furniture_equipment  0.009065
8                    Sex_female  0.007021
9                   Purpose_car  0.006882
10                 Housing_free  0.006844
11         Saving_accounts_none -0.004482
12                     Sex_male  0.004218
13       Job_unskilled_resident  0.004134
14       Saving_accounts_little -0.003987
15            Job_highlyskilled  0.002708
16   Saving_accounts_quite_rich -0.001809
17            Purpose_education  0.001744
18                  Job_skilled -0.001720
19                  Housing_own  0.001668
20              Purpose_repairs  0.001397
21      Purpose_vacation_others  0.000760
22             Purpose_business -0.000601
23         Saving_accounts_rich  0.000569
24        Checking_account_rich -0.000486
25             Purpose_radio_TV -0.000356
26                 Housing_rent  0.000178
27  Purpose_domestic_appliances  0.000000
28    Job_unskilled_nonresident  0.000000

Anchor ranking:


feature     score
0   Purpose_furniture_equipment  0.813893
1                           Age  0.503277
2                      Duration  0.433814
3       Checking_account_little  0.283093
4    Saving_accounts_quite_rich  0.000000
5               Purpose_repairs  0.000000
6              Purpose_radio_TV  0.000000
7             Purpose_education  0.000000
8   Purpose_domestic_appliances  0.000000
9                   Purpose_car  0.000000
10             Purpose_business  0.000000
11        Checking_account_rich  0.000000
12        Checking_account_none  0.000000
13    Checking_account_moderate  0.000000
14         Saving_accounts_rich  0.000000
15         Saving_accounts_none  0.000000
16                Credit_amount  0.000000
17     Saving_accounts_moderate  0.000000
18       Saving_accounts_little  0.000000
19                 Housing_rent  0.000000
20                  Housing_own  0.000000
21                 Housing_free  0.000000
22       Job_unskilled_resident  0.000000
23    Job_unskilled_nonresident  0.000000
24                  Job_skilled  0.000000
25            Job_highlyskilled  0.000000
26                     Sex_male  0.000000
27                   Sex_female  0.000000
28      Purpose_vacation_others  0.000000

### Step 2
Generate a variation of the original dataset by introducing noise.

In [10]:
def get_noisy_data_autoencoder(X: pd.DataFrame, categorical_features_names: list[str], encoding_dim: int = 5, num_features_to_replace: int = 2, epochs=500) -> pd.DataFrame:
    """
    Returns a DataFrame containing a noisy variation of the data.

    The noise is generated by swapping the values of a small number of features between a sample and a random close neighbor.
    To determine the neighbors, we use an autoencoder to reduce the dimensionality of the data and then calculate the use the NearestNeightbors algorithm in the reduced space.
    """

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    
    input_dim = X_scaled.shape[1]

    input_layer = Input(shape=(input_dim,))
    encoded = Dense(encoding_dim, activation='relu')(input_layer)
    decoded = Dense(input_dim, activation='sigmoid')(encoded)

    autoencoder = Model(inputs=input_layer, outputs=decoded)
    encoder = Model(inputs=input_layer, outputs=encoded)
    autoencoder.compile(optimizer=Adam(), loss='mean_squared_error')
    autoencoder.fit(X_scaled, X_scaled, epochs=epochs, batch_size=32, shuffle=True, validation_split=0.2)
    # Extract hidden layer representation:
    hidden_representation = encoder.predict(X_scaled)

    # Compute Nearest Neighbors using hidden_representation
    nbrs = NearestNeighbors(n_neighbors=5, algorithm='auto').fit(hidden_representation) # TODO: here, hidden_representation is just the autoencoder fit to the scaled X data; see if this is the way to do this
    distances, indices = nbrs.kneighbors(hidden_representation)

    X_noisy = X.copy()

    # Get id's of columns that belong to the same categorical feature (after being one-hot-encodeded);
    # Columns that belong to the same categorical feature start with the same name, and will be treated as a single feature when adding noise.
    categorical_features_indices = [
        [X.columns.get_loc(col_name) for col_name in X.columns if col_name.startswith(feature)]
        for feature in categorical_features_names
    ]

    # Replace features with random neighbor's features
    for i in range(X.shape[0]):  # Iterate over each sample
        available_features_to_replace = list(range(X.shape[1]))
        for j in range(num_features_to_replace):
            # Select features to replace; if the feture selected belong to one of the lists in categorical_features_indices, we will replace all the features in that list
            features_to_replace = np.random.choice(available_features_to_replace, 1)
            for feature_indices in categorical_features_indices:
                if features_to_replace in feature_indices:
                    features_to_replace = feature_indices
                    break
            
            # Remove the selected features from the list of available features to replace
            available_features_to_replace = [f for f in available_features_to_replace if f not in features_to_replace]

            # Choose a random neighbor from the nearest neighbors
            neighbor_idx = np.random.choice(indices[i][1:])

            # Replace the selected features with the neighbor's features
            X_noisy.iloc[i, features_to_replace] = X.iloc[neighbor_idx, features_to_replace]

    return X_noisy

In [11]:
# Example of usage:
display(X.shape)
noisy_data = get_noisy_data_autoencoder(X, categorical_features_names=categorical_features, encoding_dim=5, num_features_to_replace=2, epochs=10)

# Split the noisy data the same way as the original data
# X_train_noisy, X_test_noisy = train_test_split(noisy_data, test_size=0.2, random_state=41) # Split it with the same random_state as the original data
X_train_noisy = noisy_data.loc[X_train.index]
X_test_noisy = noisy_data.loc[X_test.index]
display("Mean Absolute Difference: ", np.mean(np.abs(X - noisy_data)))

(954, 29)

Epoch 1/10


W0000 00:00:1730833632.007401   37587 gpu_device.cc:2344] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.2719 - val_loss: 1.2013
Epoch 2/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.2502 - val_loss: 1.1780
Epoch 3/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.2064 - val_loss: 1.1558
Epoch 4/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.2396 - val_loss: 1.1344
Epoch 5/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - loss: 1.2078 - val_loss: 1.1133
Epoch 6/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - loss: 1.1550 - val_loss: 1.0924
Epoch 7/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.1535 - val_loss: 1.0722
Epoch 8/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.1266 - val_loss: 1.0523
Epoch 9/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.1106 - val_loss: 1.0334
Epoch 10/10
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - loss: 1.1193 - val_loss: 1.0156
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 556us/step


'Mean Absolute Difference: '

5.053675992192583

### Step 3
Repeat step 1 on this noisy dataset to obtain a new set of feature importance rankings.

In [12]:
# Given a single instance, get rankings for original and noisy data, then compare them (next steps).
feature_importances_noisy = FeatureImportanceCalculator(clf, X_train_noisy)

lime_ranking_noisy = feature_importances_noisy.get_lime_ranking(X_test_noisy.iloc[sample_idx])
shap_ranking_noisy = feature_importances_noisy.get_shap_ranking(X_test_noisy.iloc[sample_idx], explainer_type=shap.TreeExplainer)
anchor_ranking_noisy = feature_importances_noisy.get_anchor_ranking(X_test_noisy.iloc[sample_idx])

display(lime_ranking_noisy, shap_ranking_noisy, anchor_ranking_noisy)

feature     score
0         Checking_account_none -0.062187
1                      Duration  0.058268
2       Checking_account_little  0.038214
3                           Age -0.023416
4     Checking_account_moderate  0.018128
5                   Housing_own -0.014083
6              Purpose_radio_TV -0.011856
7        Saving_accounts_little  0.009520
8                 Credit_amount  0.009159
9                      Sex_male -0.007348
10                 Housing_free  0.005491
11                 Housing_rent  0.005124
12                  Purpose_car  0.004945
13         Saving_accounts_rich -0.004548
14         Saving_accounts_none -0.004395
15            Job_highlyskilled  0.003334
16       Job_unskilled_resident  0.003224
17    Job_unskilled_nonresident -0.002798
18     Saving_accounts_moderate  0.002475
19                   Sex_female  0.002411
20      Purpose_vacation_others -0.002378
21            Purpose_education  0.001651
22  Purpose_furniture_equipment  0.001198
23             Purpose_business  0.001107
24  Purpose_domestic_appliances -0.000787
25                  Job_skilled  0.000625
26        Checking_account_rich  0.000200
27   Saving_accounts_quite_rich  0.000131
28              Purpose_repairs -0.000032

feature     score
0         Checking_account_none -0.054826
1                      Duration  0.043885
2       Checking_account_little  0.039921
3                 Credit_amount  0.033787
4                           Age  0.029161
5     Checking_account_moderate -0.020015
6        Saving_accounts_little -0.014250
7   Purpose_furniture_equipment  0.012618
8                  Housing_free  0.009376
9                   Purpose_car  0.008721
10                  Housing_own  0.006562
11         Saving_accounts_none -0.006188
12     Saving_accounts_moderate  0.005833
13       Job_unskilled_resident  0.005104
14             Purpose_radio_TV -0.003679
15                 Housing_rent -0.002224
16              Purpose_repairs  0.002188
17             Purpose_business  0.001501
18   Saving_accounts_quite_rich -0.001412
19                  Job_skilled  0.001266
20        Checking_account_rich -0.001130
21            Job_highlyskilled  0.000947
22         Saving_accounts_rich  0.000754
23            Purpose_education  0.000686
24      Purpose_vacation_others  0.000510
25                   Sex_female  0.000189
26                     Sex_male -0.000103
27  Purpose_domestic_appliances  0.000017
28    Job_unskilled_nonresident  0.000000

feature     score
0                           Age  0.503277
1                      Duration  0.433814
2                   Job_skilled  0.369594
3                   Housing_own  0.296199
4       Checking_account_little  0.283093
5          Saving_accounts_rich  0.000000
6               Purpose_repairs  0.000000
7              Purpose_radio_TV  0.000000
8   Purpose_furniture_equipment  0.000000
9             Purpose_education  0.000000
10  Purpose_domestic_appliances  0.000000
11                  Purpose_car  0.000000
12             Purpose_business  0.000000
13        Checking_account_rich  0.000000
14        Checking_account_none  0.000000
15    Checking_account_moderate  0.000000
16         Saving_accounts_none  0.000000
17   Saving_accounts_quite_rich  0.000000
18                Credit_amount  0.000000
19     Saving_accounts_moderate  0.000000
20       Saving_accounts_little  0.000000
21                 Housing_rent  0.000000
22                 Housing_free  0.000000
23       Job_unskilled_resident  0.000000
24    Job_unskilled_nonresident  0.000000
25            Job_highlyskilled  0.000000
26                     Sex_male  0.000000
27                   Sex_female  0.000000
28      Purpose_vacation_others  0.000000

### Step 4
Assess the robustness of each explanation model by comparing its feature importance ranking on the original data with the ranking on the noisy data.

In [13]:
def robustness_metrics(ranking_original: pd.DataFrame, ranking_noisy: pd.DataFrame) -> pd.DataFrame:
    """
    Returns a DataFrame with 4 robustness metrics of a given feature importance ranking:
        1. "mean_squared_differece": the mean squared difference between the scores of the original and noisy rankings; (previously called "stability") | Lower is better
        2. "mean_absolute_difference": the mean absolute difference between the scores of the original and noisy rankings; (previously called "sensitivity") | Lower is better
        3. "spearman_correlation": the Spearman correlation | Higher is better
        4. "pearson_correlation": the Pearson correlation | Higher is better
    """
    
    # Align dataframes:
    ranking_original = ranking_original.set_index('feature')
    ranking_noisy = ranking_noisy.set_index('feature')
    ranking_original = ranking_original.reindex(ranking_noisy.index)

    # Compute metrics:
    mean_squared_difference = ((ranking_original['score'] - ranking_noisy['score']) ** 2).mean()
    mean_absolute_difference = np.abs(ranking_original['score'] - ranking_noisy['score']).mean()
    spearman_correlation = spearmanr(ranking_original['score'], ranking_noisy['score']).correlation
    pearson_correlation = pearsonr(ranking_original['score'], ranking_noisy['score'])[0]

    robustness_metrics = pd.DataFrame({
        'mean_squared_difference': [mean_squared_difference],
        'mean_absolute_difference': [mean_absolute_difference],
        'spearman_correlation': [spearman_correlation],
        'pearson_correlation': [pearson_correlation]
    })

    return robustness_metrics

In [14]:
print("Robustness metrics for LIME:")
display(robustness_metrics(lime_ranking, lime_ranking_noisy))

print("Robustness metrics for SHAP:")
display(robustness_metrics(shap_ranking, shap_ranking_noisy))

print("Robustness metrics for Anchor:")
display(robustness_metrics(anchor_ranking, anchor_ranking_noisy))

Robustness metrics for LIME:


mean_squared_difference  mean_absolute_difference  spearman_correlation  \
0                 0.000007                  0.002331               0.84532   

   pearson_correlation  
0             0.990246

Robustness metrics for SHAP:


mean_squared_difference  mean_absolute_difference  spearman_correlation  \
0                 0.000033                  0.004022              0.840744   

   pearson_correlation  
0             0.948501

Robustness metrics for Anchor:


mean_squared_difference  mean_absolute_difference  spearman_correlation  \
0                 0.030578                  0.051024              0.601373   

   pearson_correlation  
0             0.483254

### Step 5

In [15]:
def explain_instance(instance_data_row):
    lime_ranking = feature_importances.get_lime_ranking(instance_data_row)
    lime_ranking_noisy = feature_importances_noisy.get_lime_ranking(instance_data_row)
    lime_instance_metrics = robustness_metrics(lime_ranking, lime_ranking_noisy)

    shap_ranking = feature_importances.get_shap_ranking(instance_data_row, explainer_type=shap.TreeExplainer)
    shap_ranking_noisy = feature_importances_noisy.get_shap_ranking(instance_data_row, explainer_type=shap.TreeExplainer)
    shap_instance_metrics = robustness_metrics(shap_ranking, shap_ranking_noisy)

    anchor_ranking = feature_importances.get_anchor_ranking(instance_data_row)
    anchor_ranking_noisy = feature_importances_noisy.get_anchor_ranking(instance_data_row)
    anchor_instance_metrics = robustness_metrics(anchor_ranking, anchor_ranking_noisy)

    ### Use toposis to assign weights to the explanation models:
    evaluation_matrix = np.array([
        lime_instance_metrics.values.flatten(),
        shap_instance_metrics.values.flatten(),
        anchor_instance_metrics.values.flatten()
    ])

    display(evaluation_matrix)

    robustness_metrics_weights = [
        0.25, # mean squared difference
        0.25, # mean absolute difference
        0.25, # spearman correlation
        0.25  # pearson correlation
    ]

    # if higher value is preferred - True
    # if lower value is preferred - False
    criterias = np.array([
        False,  # For mean_squared_difference, lower is better
        False,  # For mean_absolute_difference, lower is better
        True,   # For spearman_correlation, higher is better
        True    # For pearson_correlation, higher is better
    ])

    t = Topsis(evaluation_matrix, robustness_metrics_weights, criterias, debug=True)
    t.calc()

    display(t.best_similarity)
    display(t.worst_similarity)
    display(t.rank_to_best_similarity())


In [18]:
sample_idx = 0
explain_instance(X_test.iloc[sample_idx])

array([[0.00000896, 0.00257317, 0.90344828, 0.98730935],
       [0.0000033 , 0.00112731, 0.98411135, 0.99560029],
       [0.01899638, 0.0420301 , 0.69041096, 0.72238333]])

Step 1 - Evaluation Matrix:
 [[0.00000896 0.00257317 0.90344828 0.98730935]
 [0.0000033  0.00112731 0.98411135 0.99560029]
 [0.01899638 0.0420301  0.69041096 0.72238333]]

Step 2 - Normalized Evaluation Matrix:
 [[0.00047148 0.06108585 0.60078395 0.62595377]
 [0.00017376 0.02676172 0.65442408 0.63121022]
 [0.99999987 0.99777369 0.45911629 0.45799076]]

Step 3 - Weighted Normalized Evaluation Matrix
 [[0.00011787 0.01527146 0.15019599 0.15648844]
 [0.00004344 0.00669043 0.16360602 0.15780255]
 [0.24999997 0.24944342 0.11477907 0.11449769]]

Step 4 - worst_alternatives | best_alternatives 
 [0.24999997 0.24944342 0.11477907 0.11449769]  |  [0.00004344 0.00669043 0.16360602 0.15780255]

Step 5 - Distances to Worst Alternative | Distances to Best Alternative
 [0.34683591 0.35449494 0.        ] [0.01597484 0.         0.35449494]

Step 6 - Similarites to Worst Alternative | Similarities to Best Alternative
 [0.95596922 1.         0.        ] [0.04403078 0.         1.        ]



array([0.04403078, 0.        , 1.        ])

array([0.95596922, 1.        , 0.        ])

[2, 1, 3]

### Pevious attempt at step 5 (IGNORE)